language: node_js
node_js:
  - "0.10"
  - "0.11"

branches:
  except:
   - experimental

before_script: "npm install -g codeclimate-test-reporter"
script: "make test-travis"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acf1870e9d223c65e8d5
    on_success: change
    on_failure: always
    on_start: false
