---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
 - "5.0"
 - "4.0"
 - iojs
 - "0.10"
 - "0.12"

script: make test-travis
after_success:
 - ./scripts/travis/setup-git.sh
 - ./scripts/travis/merge-development-with-master.sh

notifications:
  slack: babeljs:5Wy4QX13KVkGy9CnU0rmvgeK
