sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"

before_install:
    # Rollup doesn't support node < 4.x. Switch to latest for build
  - . $HOME/.nvm/nvm.sh
  - nvm install stable && nvm use stable

before_script:
  - 'if [ -n "${BABEL-}" ]; then make bootstrap-babel ; fi'
  - 'BABEL_ENV=test npm run build'
    # Switch back to node version currently being tested prior to test run
  - 'nvm use $TRAVIS_NODE_VERSION;'

script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -n "${FLOW-}" ]; then npm run flow ; fi'
  - 'if [ -n "${BABEL-}" ]; then make test-babel ; fi'
  - 'if [ -z "${LINT-}" ] && [ -z "${FLOW-}" ] && [ -z "${BABEL-}" ]; then npm run test-ci ; fi'

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
    - node_js: "node"
      env: FLOW=true
    - node_js: "node"
      env: BABEL=true

after_success: 'if [ -z "${LINT-}" ] && [ -z "${FLOW-}" ] && [ -z "${BABEL-}" ]; then npm run coverage ; fi'

notifications:
  slack: babeljs:5Wy4QX13KVkGy9CnU0rmvgeK
