blank_issues_enabled: false
contact_links:
  - name: ðŸ“¦ "No matching version found"
    url: https://gist.github.com/hzoo/df94af2d2ec48696e683b772c775aa67
    about: You may have an npm error related to proxies/caching.
  - name: ðŸ—£ Ask a Question, Discuss
    url: https://github.com/babel/babel/discussions
    about: How does X work ðŸ¤”? I made this! I have an idea...
  - name: ðŸ’¡ Propose an RFC
    url: https://github.com/babel/rfcs
    about: To suggest a new option or substantial change.
  - name: ðŸ¤— Support the Project
    url: https://github.com/sponsors/babel
    about: Support the Babel team financially.
