name: Auto Rebase

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull Request number
        required: true

permissions:
  contents: read

jobs:
  rebase:
    permissions:
      contents: read # to fetch code
      pull-requests: read # to get PR metadata
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request branch
        uses: actions/github-script@v8
        id: pr-meta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pull_request }},
            });

            const {
              ref: branch,
              repo: { full_name: repository }
            } = pullRequest.head;

            const fs = require("fs");
            const { GITHUB_OUTPUT } = process.env;
            fs.appendFileSync(GITHUB_OUTPUT, `branch=${branch}\n`);
            fs.appendFileSync(GITHUB_OUTPUT, `repository=${repository}\n`);

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr-meta.outputs.repository }}
          ref: ${{ steps.pr-meta.outputs.branch }}
          fetch-depth: 0 # Otherwise we cannot push
          persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          cache: "yarn"

      - name: Config git
        run: |
          git config user.name "Babel Bot"
          git config user.email "babel-bot@users.noreply.github.com"

      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: rebase } = await import('${{ github.workspace }}/scripts/actions/auto-rebase.ts');
            await rebase(github, context, ${{ github.event.inputs.pull_request }});

      - name: Commit updates
        run: |
          git push -f "https://babel-bot:${{ secrets.BOT_TOKEN }}@github.com/${{ steps.pr-meta.outputs.repository }}.git" ${{ steps.pr-meta.outputs.branch }}
