name: E2E tests (breaking, esm)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-publish:
    name: Publish to local Verdaccio registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          cache: "yarn"
      - name: Use ESM
        run: make use-esm
      - name: Publish
        run: ./scripts/integration-tests/publish-local.sh
        env:
          BABEL_8_BREAKING: true
          USE_ESM: true
      - name: Pack published packages
        working-directory: /tmp
        run: tar -cvf verdaccio-workspace.tar verdaccio-workspace
      - uses: actions/upload-artifact@v3
        with:
          name: verdaccio-workspace
          path: /tmp/verdaccio-workspace.tar
          retention-days: 1

  e2e-tests:
    name: Test
    needs: e2e-publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # todo: verify which of these tests can be re-enabled
        project:
          - babel
          - babel7plugins-babel8core
          - create-react-app
          # - vue-cli
          # - jest
          # todo: Enable this test when metro-source-map does not reassign NodePath cache
          # https://github.com/facebook/metro/blob/29bb5f2ad3319ba8f4764c3993aa85c15f59af23/packages/metro-source-map/src/generateFunctionMap.js#L182
          # react-native
          - prettier
          # - angular-cli
    steps:
      - name: Get yarn1 cache directory path
        id: yarn1-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "*"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Use yarn1 cache
        uses: actions/cache@v4
        id: yarn1-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn1-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn1-e2e-breaking-${{ matrix.project }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn1-e2e-breaking-${{ matrix.project }}-
      - name: Use yarn cache
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-e2e-breaking-${{ matrix.project }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-e2e-breaking-${{ matrix.project }}-
      - name: Clean babel cache
        run: |
          rm -rf ${{ steps.yarn1-cache-dir-path.outputs.dir }}/*babel*
          rm -rf ${{ steps.yarn-cache-dir-path.outputs.dir }}/*babel*
      - uses: actions/download-artifact@v3
        with:
          name: verdaccio-workspace
          path: /tmp
      - name: Unpack published packages
        run: tar -C /tmp -xf /tmp/verdaccio-workspace.tar
      - name: Test
        run: ./scripts/integration-tests/e2e-${{ matrix.project }}.sh
        env:
          USE_ESM: true
          BABEL_8_BREAKING: true
