name: Open issue to remind doing something
on:
  schedule:
    - cron: 0 0 15 07 *

permissions:
  issues: write

jobs:
  npm_deprecate:
    name: Create issue for deprecating npm packages
    runs-on: ubuntu-latest
    steps:
      - name: Issue Bot Action
        uses: imjohnbo/issue-bot@v3.4.3
        with:
          assignees: nicolo-ribaudo
          title: "Deprecate renamed npm packages"
          body: |-
            Please run these commands:
            ```
            npm deprecate @babel/plugin-proposal-duplicate-named-capturing-groups-regex "This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-duplicate-named-capturing-groups-regex instead."
            ```
